### ISSUE TITLE
Write docker-compose file

### ISSUE THREAD

**Issue by jtemporal** [okfn-brasil/notebooks#17]
**What is the problem?** 

The docker command to run jupyter server isn't very friendly. Maybe write a docker-compose too and give that option would be better.

**How can this be addressed?**

Checkout the [docker-compose documentatiomn](https://docs.docker.com/compose/gettingstarted/#step-3-define-services-in-a-compose-file)

**Who could help with this issue?**

me o/

**Comment by thiagoalmeidasa** [comment]
I'll add on this PR #18 .

**Comment by thiagoalmeidasa** [comment]
Hey, on this docker-compose is better to make a local build or to use the pre-built docker image from docker hub?

**Comment by jtemporal** [comment]
the idea is to use the `okbr/serenata-notebooks` image :wink:

**Comment by thiagoalmeidasa** [comment]
Thanks for letting me know.

Is there any reason for us to use `continuum/miniconda3` as base image instead of some more specific jupyter image like any of  [jupyter-docker-stacks](http://jupyter-docker-stacks.readthedocs.io) ?

**Comment by jtemporal** [comment]
@thiagoalmeidasa because the jupyter ones were very heavy, the miniconda one gives an image with half the weight :wink:

**Comment by JinnaBalu** [comment]
Hi @jtemporal , I can write docker-compose and instruction for dockerisation. I see the codebase dependent deployment. If you allow me i can start on that, merge @thiagoalmeidasa  changes so that i can start or. or i can start without depending on @thiagoalmeidasa  chnages.

**Comment by jtemporal** [comment]
@JinnaBalu go ahead, just keep in mind that we already have an [image on docker hub](https://hub.docker.com/r/okbr/serenata-notebooks/) to facilitate things and it would be awesome if it was a better one :smile: 

looknig forward to this PR

**Comment by JinnaBalu** [comment]
@jtemporal Created the PR https://github.com/okfn-brasil/notebooks/pull/20

**Comment by jtemporal** [comment]
I'm closing this one because docker compose file and necessary documentation was created... I believe further discussions should be carried out in a new issue ;)

thank you all
