### ISSUE TITLE
Update Docker-compose to pull pre-existing image

### ISSUE THREAD

**Issue by jtemporal** [okfn-brasil/notebooks#21]
**What is the problem?** 

Our `docker-compose.yml` build the image locally, but there's a pre-built image on docker hub for this project [as you can see here](https://hub.docker.com/r/okbr/serenata-notebooks/)

**How can this be addressed?**

change the [line 7 on the docker-compose.yml](https://github.com/okfn-brasil/notebooks/blob/master/docker-compose.yml#L7), instead of `build: .` use the image key like: 
```
image: okbr/serenata-notebooks
```

**Who could help with this issue?**

me o/

**Comment by jtemporal** [comment]
go ahead @darellkoh all yours :+1:

**Comment by darellkoh** [comment]
@jtemporal Thanks! I'll have a PR ready shortly.

**Comment by JinnaBalu** [comment]
@jtemporal Added PR check https://github.com/okfn-brasil/notebooks/pull/22

**Comment by darellkoh** [comment]
Is this issue still open? It seems like there's already a PR for it but it wasn't clear that it had been claimed.

**Comment by cuducos** [comment]
> Is this issue still open? It seems like there's already a PR for it but it wasn't clear that it had been claimed.

Yes. #20 and #22 were closed because they were overcomplicating stuff and @JinnaBalu was insisting in stuff maintainers agreed not to incorporate (such as deploy, Docker registry and tag). The idea is to KISS just to allow users to quickly get started.

**Comment by jtemporal** [comment]
@darellkoh this issue is yours if you still want it ;) looking forward for your PR :)

**Comment by darellkoh** [comment]
@jtemporal I do! I have the PR ready on a branch but I'm experiencing auth issues with being able to push to the remote. Looking into that now. Apologies in advance, I'm a first-time contributor.

**Comment by darellkoh** [comment]
@cuducos That definitely fixed it! Thanks for being patient <3 I've made the PR here: https://github.com/okfn-brasil/notebooks/pull/23. Please feel free to point out if I'm missing anything, thanks so much.

**Comment by jtemporal** [comment]
closed by #23 thanks @darellkoh  for the contribution :heart:
